imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  externalPlugins:
    luxEmail4Link:
      resource: 'EXT:lux/Resources/Public/JavaScript/Static/CkEditorPlugins/luxEmail4Link/plugin.js'

  config:
    extraAllowedContent: 'a[data-*];'
    contentsCss: ['EXT:winkelbach_distribution/Resources/Public/Css/rte.css']

    toolbarGroups:
        - { name: styles, groups: [ format, styles ] }
        - { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] }
        - { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] }
        - "/"
        - { name: 'links', groups: [ 'links', 'Email4Link' ] } 
        - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
        - { name: editing, groups: [ spellchecker ] }
        - { name: insert, groups: [ insert ] }
        - { name: tools, groups: [ table, specialchar ] }
        - { name: document, groups: [ mode ] }

    format_tags: "p;h1;h2;h3;h4;h5;pre"

    justifyClasses:
        - text-left
        - text-center
        - text-right
        - text-justify

    extraPlugins:
        - justify

    removePlugins:
        - image

    removeButtons:
        - Anchor
        - Underline
        - Strike
